# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/akay729/Documenti/UE582

TARGETS = \
	ChaosTestHarness \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	Tron-Android-DebugGame  \
	Tron-Android-Development  \
	Tron-Android-Shipping  \
	Tron-Linux-DebugGame  \
	Tron-Linux-Development  \
	Tron-Linux-Shipping  \
	Tron-LinuxArm64-DebugGame  \
	Tron-LinuxArm64-Development  \
	Tron-LinuxArm64-Shipping  \
	Tron \
	TronEditor-Linux-DebugGame  \
	TronEditor-Linux-Development  \
	TronEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend TronEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug TronEditor-Linux-Debug


ChaosTestHarness: ChaosTestHarness-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

Tron-Android-DebugGame:
	 $(BUILD) Tron Android DebugGame  -Project="/home/akay729/Documenti/UEProjects/T-R-O-N/Tron.uproject" $(ARGS)

Tron-Android-Development:
	 $(BUILD) Tron Android Development  -Project="/home/akay729/Documenti/UEProjects/T-R-O-N/Tron.uproject" $(ARGS)

Tron-Android-Shipping:
	 $(BUILD) Tron Android Shipping  -Project="/home/akay729/Documenti/UEProjects/T-R-O-N/Tron.uproject" $(ARGS)

Tron-Linux-DebugGame:
	 $(BUILD) Tron Linux DebugGame  -Project="/home/akay729/Documenti/UEProjects/T-R-O-N/Tron.uproject" $(ARGS)

Tron-Linux-Development:
	 $(BUILD) Tron Linux Development  -Project="/home/akay729/Documenti/UEProjects/T-R-O-N/Tron.uproject" $(ARGS)

Tron-Linux-Shipping:
	 $(BUILD) Tron Linux Shipping  -Project="/home/akay729/Documenti/UEProjects/T-R-O-N/Tron.uproject" $(ARGS)

Tron-LinuxArm64-DebugGame:
	 $(BUILD) Tron LinuxArm64 DebugGame  -Project="/home/akay729/Documenti/UEProjects/T-R-O-N/Tron.uproject" $(ARGS)

Tron-LinuxArm64-Development:
	 $(BUILD) Tron LinuxArm64 Development  -Project="/home/akay729/Documenti/UEProjects/T-R-O-N/Tron.uproject" $(ARGS)

Tron-LinuxArm64-Shipping:
	 $(BUILD) Tron LinuxArm64 Shipping  -Project="/home/akay729/Documenti/UEProjects/T-R-O-N/Tron.uproject" $(ARGS)

Tron: Tron-Linux-Development

TronEditor-Linux-DebugGame:
	 $(BUILD) TronEditor Linux DebugGame  -Project="/home/akay729/Documenti/UEProjects/T-R-O-N/Tron.uproject" $(ARGS)

TronEditor-Linux-Development:
	 $(BUILD) TronEditor Linux Development  -Project="/home/akay729/Documenti/UEProjects/T-R-O-N/Tron.uproject" $(ARGS)

TronEditor: TronEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/akay729/Documenti/UEProjects/T-R-O-N/Tron.uproject" -Game 

.PHONY: $(TARGETS)
